import * as z from "zod";

export const TypeSchema = z.enum([
    "article",
    "article-journal",
    "article-magazine",
    "article-newspaper",
    "bill",
    "book",
    "broadcast",
    "chapter",
    "classic",
    "collection",
    "dataset",
    "document",
    "entry",
    "entry-dictionary",
    "entry-encyclopedia",
    "event",
    "figure",
    "graphic",
    "hearing",
    "interview",
    "legal_case",
    "legislation",
    "manuscript",
    "map",
    "motion_picture",
    "musical_score",
    "pamphlet",
    "paper-conference",
    "patent",
    "performance",
    "periodical",
    "personal_communication",
    "post",
    "post-weblog",
    "regulation",
    "report",
    "review",
    "review-book",
    "software",
    "song",
    "speech",
    "standard",
    "thesis",
    "treaty",
    "webpage",
]);
export type Type = z.infer<typeof TypeSchema>;

export const DateContentModelSchema = z.object({
    "circa": z.union([z.boolean(), z.number(), z.string()]).optional(),
    "date-parts": z.array(z.array(z.union([z.number(), z.string()]))).optional(),
    "literal": z.string().optional(),
    "raw": z.string().optional(),
    "season": z.union([z.number(), z.string()]).optional(),
});
export type DateContentModel = z.infer<typeof DateContentModelSchema>;

export const NameVariableSchema = z.object({
    "comma-suffix": z.union([z.boolean(), z.number(), z.string()]).optional(),
    "dropping-particle": z.string().optional(),
    "family": z.string().optional(),
    "given": z.string().optional(),
    "literal": z.string().optional(),
    "non-dropping-particle": z.string().optional(),
    "parse-names": z.union([z.boolean(), z.number(), z.string()]).optional(),
    "static-ordering": z.union([z.boolean(), z.number(), z.string()]).optional(),
    "suffix": z.string().optional(),
});
export type NameVariable = z.infer<typeof NameVariableSchema>;

export const CSLDataSchema = z.object({
    "abstract": z.string().optional(),
    "accessed": DateContentModelSchema.optional(),
    "annote": z.string().optional(),
    "archive": z.string().optional(),
    "archive-place": z.string().optional(),
    "archive_collection": z.string().optional(),
    "archive_location": z.string().optional(),
    "author": z.array(NameVariableSchema).optional(),
    "authority": z.string().optional(),
    "available-date": DateContentModelSchema.optional(),
    "call-number": z.string().optional(),
    "categories": z.array(z.string()).optional(),
    "chair": z.array(NameVariableSchema).optional(),
    "chapter-number": z.union([z.number(), z.string()]).optional(),
    "citation-key": z.string().optional(),
    "citation-label": z.string().optional(),
    "citation-number": z.union([z.number(), z.string()]).optional(),
    "collection-editor": z.array(NameVariableSchema).optional(),
    "collection-number": z.union([z.number(), z.string()]).optional(),
    "collection-title": z.string().optional(),
    "compiler": z.array(NameVariableSchema).optional(),
    "composer": z.array(NameVariableSchema).optional(),
    "container-author": z.array(NameVariableSchema).optional(),
    "container-title": z.string().optional(),
    "container-title-short": z.string().optional(),
    "contributor": z.array(NameVariableSchema).optional(),
    "curator": z.array(NameVariableSchema).optional(),
    "custom": z.record(z.string(), z.any()).optional(),
    "dimensions": z.string().optional(),
    "director": z.array(NameVariableSchema).optional(),
    "division": z.string().optional(),
    "DOI": z.string().optional(),
    "edition": z.union([z.number(), z.string()]).optional(),
    "editor": z.array(NameVariableSchema).optional(),
    "editorial-director": z.array(NameVariableSchema).optional(),
    "event": z.string().optional(),
    "event-date": DateContentModelSchema.optional(),
    "event-place": z.string().optional(),
    "event-title": z.string().optional(),
    "executive-producer": z.array(NameVariableSchema).optional(),
    "first-reference-note-number": z.union([z.number(), z.string()]).optional(),
    "genre": z.string().optional(),
    "guest": z.array(NameVariableSchema).optional(),
    "host": z.array(NameVariableSchema).optional(),
    "id": z.union([z.number(), z.string()]).optional(),
    "illustrator": z.array(NameVariableSchema).optional(),
    "interviewer": z.array(NameVariableSchema).optional(),
    "ISBN": z.string().optional(),
    "ISSN": z.string().optional(),
    "issue": z.union([z.number(), z.string()]).optional(),
    "issued": DateContentModelSchema.optional(),
    "journalAbbreviation": z.string().optional(),
    "jurisdiction": z.string().optional(),
    "keyword": z.string().optional(),
    "language": z.string().optional(),
    "locator": z.union([z.number(), z.string()]).optional(),
    "medium": z.string().optional(),
    "narrator": z.array(NameVariableSchema).optional(),
    "note": z.string().optional(),
    "number": z.union([z.number(), z.string()]).optional(),
    "number-of-pages": z.union([z.number(), z.string()]).optional(),
    "number-of-volumes": z.union([z.number(), z.string()]).optional(),
    "organizer": z.array(NameVariableSchema).optional(),
    "original-author": z.array(NameVariableSchema).optional(),
    "original-date": DateContentModelSchema.optional(),
    "original-publisher": z.string().optional(),
    "original-publisher-place": z.string().optional(),
    "original-title": z.string().optional(),
    "page": z.union([z.number(), z.string()]).optional(),
    "page-first": z.union([z.number(), z.string()]).optional(),
    "part": z.union([z.number(), z.string()]).optional(),
    "part-title": z.string().optional(),
    "performer": z.array(NameVariableSchema).optional(),
    "PMCID": z.string().optional(),
    "PMID": z.string().optional(),
    "printing": z.union([z.number(), z.string()]).optional(),
    "producer": z.array(NameVariableSchema).optional(),
    "publisher": z.string().optional(),
    "publisher-place": z.string().optional(),
    "recipient": z.array(NameVariableSchema).optional(),
    "references": z.string().optional(),
    "reviewed-author": z.array(NameVariableSchema).optional(),
    "reviewed-genre": z.string().optional(),
    "reviewed-title": z.string().optional(),
    "scale": z.string().optional(),
    "script-writer": z.array(NameVariableSchema).optional(),
    "section": z.string().optional(),
    "series-creator": z.array(NameVariableSchema).optional(),
    "shortTitle": z.string().optional(),
    "source": z.string().optional(),
    "status": z.string().optional(),
    "submitted": DateContentModelSchema.optional(),
    "supplement": z.union([z.number(), z.string()]).optional(),
    "title": z.string().optional(),
    "title-short": z.string().optional(),
    "translator": z.array(NameVariableSchema).optional(),
    "type": TypeSchema,
    "URL": z.string().optional(),
    "version": z.string().optional(),
    "volume": z.union([z.number(), z.string()]).optional(),
    "volume-title": z.string().optional(),
    "volume-title-short": z.string().optional(),
    "year-suffix": z.string().optional(),
});
export type CSLData = z.infer<typeof CSLDataSchema>;
